/*------------------------------ WATERMARK FUNCTION ON SERCH ONCLICK--------------------------- */
function watermarkreport(){	
	var army_no = localStorage.getItem("army_no");
	
	Array.from(document.querySelectorAll('.watermarked')).forEach(function (el) {
		var wtmarklbl=" Generated by "+username;
		if(army_no != "" & army_no != null){
			wtmarklbl +=" ["+army_no+"]";
		}
		wtmarklbl += " on "+ curDate;	
		
		el.dataset.watermark = (wtmarklbl + ' ').repeat(20000);
	});	
}
function nrSetWaterMark(pline){
	var ab="";
	abip="Generated by " + username +" ["+army_no+"] on "+curDate;
	for (var i = 0; i <pline*2; i++) {
		ab=ab+abip+" ";
	}
	$(".nrWatermarkBase p").text(ab);
}

//FP Function Start 
if(typeof String.prototype.replaceAll == "undefined"){
	String.prototype.replaceAll = function(str1,str2){
	    //var reg = new RegExp(str1,'g');
	    //var val = this.valueOf().replace(reg,str2)
		var val = this.valueOf().split(str1).join(str2);
	    return val;
	}
}
 

Number.prototype.toINR = function(curSymbol,rsType,rsFmt,rsType2){
	
	if (!rsType2) {
		rsType2=rsType;
	}	
	if (rsType==rsType2) {
		if (rsType2=='CR') {
			var nRetval=parseFloat(this.valueOf()/1).toFixed(5);
		} else {
			var nRetval=parseFloat(this.valueOf()/1).toFixed(2);	
		}	
	} else {
		if (rsType !='CR' && rsType2=='CR') {
			if (rsType2=='CR') {
				var nRetval=parseFloat(this.valueOf()/10000000).toFixed(5);
			} else {
				var nRetval=parseFloat(this.valueOf()/10000000).toFixed(2);
			}
		} else {
			if (rsType =='CR' && rsType2 !='CR') {
				if (rsType2=='CR') {
					var nRetval=parseFloat(this.valueOf()*10000000).toFixed(5);
				} else {
					var nRetval=parseFloat(this.valueOf()*10000000).toFixed(2);
				}
			}
		}		
	}	
	
	
	curSymbol = curSymbol || '';
	if (rsFmt=='INR') {
		var nRetValInr=Number(nRetval).toINRC(curSymbol,rsType2);
	} else {
		var nRetValInr=nRetval;
	}
	//console.log(rsType,rsFmt,rsType2,nRetval,nRetValInr);
	var nRetValf=curSymbol+nRetValInr;
	return nRetValf;
}

Number.prototype.toINRR = function(curSymbol,rsType,rsFmt,rsType2){
	if (!rsType2) {
		rsType2=rsType;
	}
	curSymbol = curSymbol || '';
	if (rsType2=='CR') {
		var nRetval=parseFloat(this.valueOf()/10000000).toFixed(5);
	} else {
		var nRetval=parseFloat(this.valueOf()/1).toFixed(2);	
	}	
	if (rsFmt=='INR') {
		var nRetValInr=Number(nRetval).toINRC(curSymbol,rsType2);
	} else {
		var nRetValInr=nRetval;
	}
	var nRetValf=curSymbol+nRetValInr;
	return nRetValf;
}


Number.prototype.toINRC = function(curSymbol,rsType){
	curSymbol = curSymbol || '';	
	//var nRetval=this.valueOf().toFixed(5).toLocaleString('en-In',{currency:'INR'});;
	if (rsType=='CR') {
		var nRetval=this.valueOf().toFixed(5).replace(/(\d)(?=(\d{2})+\d\.)/g, '$1,');
	} else {
		var nRetval=this.valueOf().toFixed(2).replace(/(\d)(?=(\d{2})+\d\.)/g, '$1,');
	}
	var nRetValf=curSymbol+nRetval;
	return nRetValf;
}
//FP Function End