let watermarkAdded = false; // Flag to track if watermark has been added

function addDiagonalWatermark(selector) {
    const table = $(selector);
    const rowCount = table.find('tr').length - 1;

    // Only add watermark if it doesn't exist and there are rows
    if (rowCount > 0 && !watermarkAdded) {
        const watermarkOverlay = $('<div class="watermark-overlay"></div>');
        const watermarkText = $('<div class="watermark-text"></div>');

        const numRows = 30; 
        const numCols = 30; 

        for (let j = 0; j < numRows; j++) {
            const watermarkTextRow = $('<div class="watermark-text-row"></div>');
            for (let i = 0; i < numCols; i++) {
                         const textSpan = $('<span>Generated by ' + username +'Army no '+ army_no1 + ' on ' + curDateWithTimeStamp + " with IP " + userIP + '</span>');
                watermarkTextRow.append(textSpan);
            }
            watermarkText.append(watermarkTextRow);
        }

        watermarkOverlay.append(watermarkText);
        table.closest('.dataTables_wrapper').append(watermarkOverlay);
        watermarkAdded = true; 
    }
} 

function applyWatermark(selector) {
    $(selector).on('draw.dt page.dt length.dt', function () {      
        addDiagonalWatermark(selector);
    });
}  


$(document).ready(function() { 
    if ($('#selection').length > 0) {
		getUserIPs();
		getArmy_no();
		fetchCurrentDate();
        applyWatermark('#selection');
    } else {
        console.error("DataTable with ID 'selection' not found.");
    }
});
var userIP;
function getUserIPs() {	
	$.post("getip?" + key + "=" + value, {}, function(j) {
		userIP = j;		
	});
}



let curDateWithTimeStamp = ""; 
function fetchCurrentDate() {	
	$.post("getCurrentDateWithTimeStamp?" + key + "=" + value, {}, function(j) {
		curDateWithTimeStamp = j;		
	});
}


let army_no1 = ""; 
function getArmy_no() {	
	$.post("getarmy_no1?" + key + "=" + value, {}, function(j) {
		army_no1 = j;		
	});
}
